### ISSUE TITLE
One post with 2 images creates 2 posts in profile feed

### ISSUE THREAD

**Issue by sawyerb22** [Momentiio/momentiio-frontend#101]
When creating a post with multiple images it shows in the profile feed as if 2 posts were created.

**Comment by sawyerb22** [comment]
![Screen Shot 2020-02-02 at 1 16 22 AM](https://user-images.githubusercontent.com/3219056/73605303-ec794d80-4559-11ea-9190-f27c0c8a94d2.png)

**Comment by nickqweaver** [comment]
Fixed :)

**Comment by nickqweaver** [comment]
#100
